version: '3.8'

networks:
  devnet:
    driver: bridge

volumes:
  mysql_data:

services:
  portfolio-db:
    image: mysql:8.3
    platform: linux/amd64
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: IamRoot
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: bananas!
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - devnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  db-migration:
    build:
      context: ../db-migration
    container_name: db-migration
    depends_on:
      portfolio-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://portfolio-db:3306/portfolio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: portfolio_user
      SPRING_DATASOURCE_PASSWORD: bananas!
    networks:
      - devnet